# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49ea6600fe296c83f18eed5788f087c4cb8795cc2a3829aae9472a44d9dc67ec734c2ed7c3cfddf9b91c40443d4610f446a368edb1d5f019326128d2e76dd9f7

test:
  secret_key_base: 476941df55091de5b4ceb470c9fa57fa1e5c16d0496a8e9d84ada10163dd02a9caf7d42c5a6fbcca25c20a80e0f7412a9e94ff164b041c50f937c1b52475f23c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
